name: pre-commit

on:
  pull_request:
    branches: [ "main-dev" ]
    types: [opened, synchronize, reopened]
  push:
    branches: main-dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PRID: ${{ github.event.pull_request.number }}
      BRANCH: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Merge PR to sub-branch
        run: |
          git fetch origin pull/${PRID}/merge
          git checkout -b test FETCH_HEAD

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pre-commit==4.2.0

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.12"
      - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
      - run: echo "::add-matcher::.github/workflows/matchers/markdownlint.json"
      - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"

      - name: Run pre-commit
        run: |
          set +e
          if ! [[ $(pre-commit --version) == *"4.2.0"* ]]; then
              pip install pre-commit==4.2.0
          fi

          diff_files=$(git diff --name-only --diff-filter=ACMR ${BRANCH})
          num_diff_files=$(echo "$diff_files" | wc -l)
          echo -e "Different files between pr and ${BRANCH}:\n${diff_files}\n"

          echo "Checking codestyle by pre-commit ..."
          pre-commit run --files ${diff_files};check_error=$?

          echo "*****************************************************************"
          if [ ${check_error} != 0 ];then
              echo "Your PR codestyle check failed."
          else
              echo "Your PR codestyle check passed."
          fi
          echo "*****************************************************************"

          exit ${check_error}
